### ISSUE TITLE
Not considering multiline strings

### ISSUE THREAD

**Issue by Armagedoom** [sinelaw/xml-to-json-fast#3]
The line jumps within CDATA elements should transformed into "\n" before being returned, since [JSON doesn't accept line jumps](http://stackoverflow.com/a/2392888).

For instance, when you consider the following element:

<RESULTS><![CDATA[cisco&quot;, leap=0, stratum=2, rootdelay=1.11, rootdispersion=0.38,
peer=57920, refid=22.17.160.1, reftime=0xDA9BAF12.99028193, poll=6,
clock=0xALF9B2186.B8101444, phase=0.069, freq=59.98, error=0.02]]></RESULTS>

It is transformed to:

"cisco&quot;, leap=0, stratum=2, rootdelay=1.11, rootdispersion=0.38,
peer=57920, refid=22.17.160.1, reftime=0xDA9BAF12.99028193, poll=6,
clock=0xALF9B2186.B8101444, phase=0.069, freq=59.98, error=0.02"

Which is not readable from json, it should be this instead:

"cisco&quot;, leap=0, stratum=2, rootdelay=1.11, rootdispersion=0.38,\npeer=57920, refid=22.17.160.1, reftime=0xDA9BAF12.99028193, poll=6,\nclock=0xALF9B2186.B8101444, phase=0.069, freq=59.98, error=0.02"

**Comment by sinelaw** [comment]
Thanks! Fixed.
P.S. the problem was also in multi-line strings in xml attributes.

**Comment by Armagedoom** [comment]
Thank you so much! This library is very unique and extremely useful!
